### ISSUE TITLE
Get stellar.toml to display natively

### ISSUE THREAD

**Issue by JFWooten4** [blocktransfer/stellar-interface#1]
Right now, https://stellar.blocktransfer.io/.well-known/stellar.toml (via Jekyll, GH-Pages) pulls up a file download rather than[ just displaying the toml](https://ixinium.io/.well-known/stellar.toml) (path in docs as stellar.html)

Make the periodically-updated [stellar.toml file](https://github.com/blocktransfer/stellar-interface/blob/main/compliance/stellar.toml) resolve to https://stellar.blocktransfer.io/.well-known/stellar.toml which points to GH pages ... or, ideally a way to do it for https://**blocktransfer.io**/.well-known/stellar.toml

Completed 8/11/21 by #3 by Sepand Haghighi

**Comment by JFWooten4** [comment]
Also enable CORS on the stellar.toml so people can access this file from other sites.

**Comment by JFWooten4** [comment]
Updated engagement: https://github.com/blocktransfer/stellar-interface/pull/2

**Comment by sepandhaghighi** [comment]
Hi 

I saw your bounty in [Gitcoin](https://gitcoin.co/issue/blocktransfer/stellar-interface/1/100026184), and I'm here to give you a solution.
Unfortunately, this problem has no exact answer in this condition (Github Page) (there are some hacky solutions (like #2 ) but I think it's not something that you want)
This problem is related to `content-type` of `.toml` files, this type will be set by the server, and currently users cant change this setting in GitHub Pages (GitHub Pages supports more than 750 MIME types across 1,000s of file extensions. The list of supported MIME types is generated from the [mime-db project](https://github.com/jshttp/mime-db), you can see there `.toml` file has `application/toml` type, and this type always leads to download!!

Solution :

Move your website to [Netlify](https://netlify.com)
  1. It's free
  2. Easy setup with GitHub and Jekyll
  3. Allow users to change headers - [link](https://docs.netlify.com/routing/headers/)
  
  
Best Regards
Sepand Haghighi

**Comment by JFWooten4** [comment]
> Sepand

Ah I see. Thank you, Sepand!
